# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: unicode
  database: cinema_city__development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: cinema_city__test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: cinema_city__production
  pool: 5
